/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./../routes/~__root";
import { Route as AppImport } from "./../routes/~_app";
import { Route as OnboardingRouteImport } from "./../routes/~onboarding.route";
import { Route as AppIndexRouteImport } from "./../routes/~_app/~index.route";
import { Route as AppwalletsWalletsIndexRouteImport } from "./../routes/~_app/~(wallets)/~wallets.index.route";
import { Route as ApptransfersTransfersIndexRouteImport } from "./../routes/~_app/~(transfers)/~transfers.index.route";
import { Route as AppsettingsSettingsIndexRouteImport } from "./../routes/~_app/~(settings)/~settings.index.route";
import { Route as ApprecordsRecordsIndexRouteImport } from "./../routes/~_app/~(records)/~records.index.route";
import { Route as AppbudgetsBudgetsIndexRouteImport } from "./../routes/~_app/~(budgets)/~budgets.index.route";
import { Route as AppwalletsWalletsCreateRouteImport } from "./../routes/~_app/~(wallets)/~wallets.create.route";
import { Route as AppwalletsWalletsWalletIdRouteImport } from "./../routes/~_app/~(wallets)/~wallets.$walletId.route";
import { Route as ApptransfersTransfersCreateRouteImport } from "./../routes/~_app/~(transfers)/~transfers.create.route";
import { Route as ApprecordsRecordsCreateRouteImport } from "./../routes/~_app/~(records)/~records.create.route";
import { Route as ApprecordsRecordsRecordIdRouteImport } from "./../routes/~_app/~(records)/~records.$recordId.route";
import { Route as AppbudgetsBudgetsCreateRouteImport } from "./../routes/~_app/~(budgets)/~budgets.create.route";
import { Route as AppbudgetsBudgetsBudgetIdRouteImport } from "./../routes/~_app/~(budgets)/~budgets.$budgetId.route";
import { Route as AppwalletsWalletsWalletIdEditRouteImport } from "./../routes/~_app/~(wallets)/~wallets_.$walletId.edit.route";

// Create/Update Routes

const AppRoute = AppImport.update({
  id: "/_app",
  getParentRoute: () => rootRoute,
} as any);

const OnboardingRouteRoute = OnboardingRouteImport.update({
  path: "/onboarding",
  getParentRoute: () => rootRoute,
} as any);

const AppIndexRouteRoute = AppIndexRouteImport.update({
  path: "/",
  getParentRoute: () => AppRoute,
} as any);

const AppwalletsWalletsIndexRouteRoute = AppwalletsWalletsIndexRouteImport.update({
  path: "/wallets/",
  getParentRoute: () => AppRoute,
} as any);

const ApptransfersTransfersIndexRouteRoute = ApptransfersTransfersIndexRouteImport.update({
  path: "/transfers/",
  getParentRoute: () => AppRoute,
} as any);

const AppsettingsSettingsIndexRouteRoute = AppsettingsSettingsIndexRouteImport.update({
  path: "/settings/",
  getParentRoute: () => AppRoute,
} as any);

const ApprecordsRecordsIndexRouteRoute = ApprecordsRecordsIndexRouteImport.update({
  path: "/records/",
  getParentRoute: () => AppRoute,
} as any);

const AppbudgetsBudgetsIndexRouteRoute = AppbudgetsBudgetsIndexRouteImport.update({
  path: "/budgets/",
  getParentRoute: () => AppRoute,
} as any);

const AppwalletsWalletsCreateRouteRoute = AppwalletsWalletsCreateRouteImport.update({
  path: "/wallets/create",
  getParentRoute: () => AppRoute,
} as any);

const AppwalletsWalletsWalletIdRouteRoute = AppwalletsWalletsWalletIdRouteImport.update({
  path: "/wallets/$walletId",
  getParentRoute: () => AppRoute,
} as any);

const ApptransfersTransfersCreateRouteRoute = ApptransfersTransfersCreateRouteImport.update({
  path: "/transfers/create",
  getParentRoute: () => AppRoute,
} as any);

const ApprecordsRecordsCreateRouteRoute = ApprecordsRecordsCreateRouteImport.update({
  path: "/records/create",
  getParentRoute: () => AppRoute,
} as any);

const ApprecordsRecordsRecordIdRouteRoute = ApprecordsRecordsRecordIdRouteImport.update({
  path: "/records/$recordId",
  getParentRoute: () => AppRoute,
} as any);

const AppbudgetsBudgetsCreateRouteRoute = AppbudgetsBudgetsCreateRouteImport.update({
  path: "/budgets/create",
  getParentRoute: () => AppRoute,
} as any);

const AppbudgetsBudgetsBudgetIdRouteRoute = AppbudgetsBudgetsBudgetIdRouteImport.update({
  path: "/budgets/$budgetId",
  getParentRoute: () => AppRoute,
} as any);

const AppwalletsWalletsWalletIdEditRouteRoute = AppwalletsWalletsWalletIdEditRouteImport.update({
  path: "/wallets/$walletId/edit",
  getParentRoute: () => AppRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppImport;
      parentRoute: typeof rootRoute;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(budgets)/budgets/$budgetId": {
      id: "/_app/budgets/$budgetId";
      path: "/budgets/$budgetId";
      fullPath: "/budgets/$budgetId";
      preLoaderRoute: typeof AppbudgetsBudgetsBudgetIdRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(budgets)/budgets/create": {
      id: "/_app/budgets/create";
      path: "/budgets/create";
      fullPath: "/budgets/create";
      preLoaderRoute: typeof AppbudgetsBudgetsCreateRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(records)/records/$recordId": {
      id: "/_app/records/$recordId";
      path: "/records/$recordId";
      fullPath: "/records/$recordId";
      preLoaderRoute: typeof ApprecordsRecordsRecordIdRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(records)/records/create": {
      id: "/_app/records/create";
      path: "/records/create";
      fullPath: "/records/create";
      preLoaderRoute: typeof ApprecordsRecordsCreateRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(transfers)/transfers/create": {
      id: "/_app/transfers/create";
      path: "/transfers/create";
      fullPath: "/transfers/create";
      preLoaderRoute: typeof ApptransfersTransfersCreateRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(wallets)/wallets/$walletId": {
      id: "/_app/wallets/$walletId";
      path: "/wallets/$walletId";
      fullPath: "/wallets/$walletId";
      preLoaderRoute: typeof AppwalletsWalletsWalletIdRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(wallets)/wallets/create": {
      id: "/_app/wallets/create";
      path: "/wallets/create";
      fullPath: "/wallets/create";
      preLoaderRoute: typeof AppwalletsWalletsCreateRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(budgets)/budgets/": {
      id: "/_app/budgets/";
      path: "/budgets";
      fullPath: "/budgets";
      preLoaderRoute: typeof AppbudgetsBudgetsIndexRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(records)/records/": {
      id: "/_app/records/";
      path: "/records";
      fullPath: "/records";
      preLoaderRoute: typeof ApprecordsRecordsIndexRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(settings)/settings/": {
      id: "/_app/settings/";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AppsettingsSettingsIndexRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(transfers)/transfers/": {
      id: "/_app/transfers/";
      path: "/transfers";
      fullPath: "/transfers";
      preLoaderRoute: typeof ApptransfersTransfersIndexRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(wallets)/wallets/": {
      id: "/_app/wallets/";
      path: "/wallets";
      fullPath: "/wallets";
      preLoaderRoute: typeof AppwalletsWalletsIndexRouteImport;
      parentRoute: typeof AppImport;
    };
    "/_app/(wallets)/wallets/$walletId/edit": {
      id: "/_app/wallets/$walletId/edit";
      path: "/wallets/$walletId/edit";
      fullPath: "/wallets/$walletId/edit";
      preLoaderRoute: typeof AppwalletsWalletsWalletIdEditRouteImport;
      parentRoute: typeof AppImport;
    };
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRouteRoute: typeof AppIndexRouteRoute;
  AppbudgetsBudgetsBudgetIdRouteRoute: typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  AppbudgetsBudgetsCreateRouteRoute: typeof AppbudgetsBudgetsCreateRouteRoute;
  ApprecordsRecordsRecordIdRouteRoute: typeof ApprecordsRecordsRecordIdRouteRoute;
  ApprecordsRecordsCreateRouteRoute: typeof ApprecordsRecordsCreateRouteRoute;
  ApptransfersTransfersCreateRouteRoute: typeof ApptransfersTransfersCreateRouteRoute;
  AppwalletsWalletsWalletIdRouteRoute: typeof AppwalletsWalletsWalletIdRouteRoute;
  AppwalletsWalletsCreateRouteRoute: typeof AppwalletsWalletsCreateRouteRoute;
  AppbudgetsBudgetsIndexRouteRoute: typeof AppbudgetsBudgetsIndexRouteRoute;
  ApprecordsRecordsIndexRouteRoute: typeof ApprecordsRecordsIndexRouteRoute;
  AppsettingsSettingsIndexRouteRoute: typeof AppsettingsSettingsIndexRouteRoute;
  ApptransfersTransfersIndexRouteRoute: typeof ApptransfersTransfersIndexRouteRoute;
  AppwalletsWalletsIndexRouteRoute: typeof AppwalletsWalletsIndexRouteRoute;
  AppwalletsWalletsWalletIdEditRouteRoute: typeof AppwalletsWalletsWalletIdEditRouteRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRouteRoute: AppIndexRouteRoute,
  AppbudgetsBudgetsBudgetIdRouteRoute: AppbudgetsBudgetsBudgetIdRouteRoute,
  AppbudgetsBudgetsCreateRouteRoute: AppbudgetsBudgetsCreateRouteRoute,
  ApprecordsRecordsRecordIdRouteRoute: ApprecordsRecordsRecordIdRouteRoute,
  ApprecordsRecordsCreateRouteRoute: ApprecordsRecordsCreateRouteRoute,
  ApptransfersTransfersCreateRouteRoute: ApptransfersTransfersCreateRouteRoute,
  AppwalletsWalletsWalletIdRouteRoute: AppwalletsWalletsWalletIdRouteRoute,
  AppwalletsWalletsCreateRouteRoute: AppwalletsWalletsCreateRouteRoute,
  AppbudgetsBudgetsIndexRouteRoute: AppbudgetsBudgetsIndexRouteRoute,
  ApprecordsRecordsIndexRouteRoute: ApprecordsRecordsIndexRouteRoute,
  AppsettingsSettingsIndexRouteRoute: AppsettingsSettingsIndexRouteRoute,
  ApptransfersTransfersIndexRouteRoute: ApptransfersTransfersIndexRouteRoute,
  AppwalletsWalletsIndexRouteRoute: AppwalletsWalletsIndexRouteRoute,
  AppwalletsWalletsWalletIdEditRouteRoute: AppwalletsWalletsWalletIdEditRouteRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

export interface FileRoutesByFullPath {
  "/onboarding": typeof OnboardingRouteRoute;
  "": typeof AppRouteWithChildren;
  "/": typeof AppIndexRouteRoute;
  "/budgets/$budgetId": typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  "/budgets/create": typeof AppbudgetsBudgetsCreateRouteRoute;
  "/records/$recordId": typeof ApprecordsRecordsRecordIdRouteRoute;
  "/records/create": typeof ApprecordsRecordsCreateRouteRoute;
  "/transfers/create": typeof ApptransfersTransfersCreateRouteRoute;
  "/wallets/$walletId": typeof AppwalletsWalletsWalletIdRouteRoute;
  "/wallets/create": typeof AppwalletsWalletsCreateRouteRoute;
  "/budgets": typeof AppbudgetsBudgetsIndexRouteRoute;
  "/records": typeof ApprecordsRecordsIndexRouteRoute;
  "/settings": typeof AppsettingsSettingsIndexRouteRoute;
  "/transfers": typeof ApptransfersTransfersIndexRouteRoute;
  "/wallets": typeof AppwalletsWalletsIndexRouteRoute;
  "/wallets/$walletId/edit": typeof AppwalletsWalletsWalletIdEditRouteRoute;
}

export interface FileRoutesByTo {
  "/onboarding": typeof OnboardingRouteRoute;
  "/": typeof AppIndexRouteRoute;
  "/budgets/$budgetId": typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  "/budgets/create": typeof AppbudgetsBudgetsCreateRouteRoute;
  "/records/$recordId": typeof ApprecordsRecordsRecordIdRouteRoute;
  "/records/create": typeof ApprecordsRecordsCreateRouteRoute;
  "/transfers/create": typeof ApptransfersTransfersCreateRouteRoute;
  "/wallets/$walletId": typeof AppwalletsWalletsWalletIdRouteRoute;
  "/wallets/create": typeof AppwalletsWalletsCreateRouteRoute;
  "/budgets": typeof AppbudgetsBudgetsIndexRouteRoute;
  "/records": typeof ApprecordsRecordsIndexRouteRoute;
  "/settings": typeof AppsettingsSettingsIndexRouteRoute;
  "/transfers": typeof ApptransfersTransfersIndexRouteRoute;
  "/wallets": typeof AppwalletsWalletsIndexRouteRoute;
  "/wallets/$walletId/edit": typeof AppwalletsWalletsWalletIdEditRouteRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/onboarding": typeof OnboardingRouteRoute;
  "/_app": typeof AppRouteWithChildren;
  "/_app/": typeof AppIndexRouteRoute;
  "/_app/budgets/$budgetId": typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  "/_app/budgets/create": typeof AppbudgetsBudgetsCreateRouteRoute;
  "/_app/records/$recordId": typeof ApprecordsRecordsRecordIdRouteRoute;
  "/_app/records/create": typeof ApprecordsRecordsCreateRouteRoute;
  "/_app/transfers/create": typeof ApptransfersTransfersCreateRouteRoute;
  "/_app/wallets/$walletId": typeof AppwalletsWalletsWalletIdRouteRoute;
  "/_app/wallets/create": typeof AppwalletsWalletsCreateRouteRoute;
  "/_app/budgets/": typeof AppbudgetsBudgetsIndexRouteRoute;
  "/_app/records/": typeof ApprecordsRecordsIndexRouteRoute;
  "/_app/settings/": typeof AppsettingsSettingsIndexRouteRoute;
  "/_app/transfers/": typeof ApptransfersTransfersIndexRouteRoute;
  "/_app/wallets/": typeof AppwalletsWalletsIndexRouteRoute;
  "/_app/wallets/$walletId/edit": typeof AppwalletsWalletsWalletIdEditRouteRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/onboarding"
    | ""
    | "/"
    | "/budgets/$budgetId"
    | "/budgets/create"
    | "/records/$recordId"
    | "/records/create"
    | "/transfers/create"
    | "/wallets/$walletId"
    | "/wallets/create"
    | "/budgets"
    | "/records"
    | "/settings"
    | "/transfers"
    | "/wallets"
    | "/wallets/$walletId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/onboarding"
    | "/"
    | "/budgets/$budgetId"
    | "/budgets/create"
    | "/records/$recordId"
    | "/records/create"
    | "/transfers/create"
    | "/wallets/$walletId"
    | "/wallets/create"
    | "/budgets"
    | "/records"
    | "/settings"
    | "/transfers"
    | "/wallets"
    | "/wallets/$walletId/edit";
  id:
    | "__root__"
    | "/onboarding"
    | "/_app"
    | "/_app/"
    | "/_app/budgets/$budgetId"
    | "/_app/budgets/create"
    | "/_app/records/$recordId"
    | "/_app/records/create"
    | "/_app/transfers/create"
    | "/_app/wallets/$walletId"
    | "/_app/wallets/create"
    | "/_app/budgets/"
    | "/_app/records/"
    | "/_app/settings/"
    | "/_app/transfers/"
    | "/_app/wallets/"
    | "/_app/wallets/$walletId/edit";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  OnboardingRouteRoute: typeof OnboardingRouteRoute;
  AppRoute: typeof AppRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  OnboardingRouteRoute: OnboardingRouteRoute,
  AppRoute: AppRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/onboarding",
        "/_app"
      ]
    },
    "/onboarding": {
      "filePath": "~onboarding.route.tsx"
    },
    "/_app": {
      "filePath": "~_app.tsx",
      "children": [
        "/_app/",
        "/_app/budgets/$budgetId",
        "/_app/budgets/create",
        "/_app/records/$recordId",
        "/_app/records/create",
        "/_app/transfers/create",
        "/_app/wallets/$walletId",
        "/_app/wallets/create",
        "/_app/budgets/",
        "/_app/records/",
        "/_app/settings/",
        "/_app/transfers/",
        "/_app/wallets/",
        "/_app/wallets/$walletId/edit"
      ]
    },
    "/_app/": {
      "filePath": "~_app/~index.route.tsx",
      "parent": "/_app"
    },
    "/_app/budgets/$budgetId": {
      "filePath": "~_app/~(budgets)/~budgets.$budgetId.route.tsx",
      "parent": "/_app"
    },
    "/_app/budgets/create": {
      "filePath": "~_app/~(budgets)/~budgets.create.route.tsx",
      "parent": "/_app"
    },
    "/_app/records/$recordId": {
      "filePath": "~_app/~(records)/~records.$recordId.route.tsx",
      "parent": "/_app"
    },
    "/_app/records/create": {
      "filePath": "~_app/~(records)/~records.create.route.tsx",
      "parent": "/_app"
    },
    "/_app/transfers/create": {
      "filePath": "~_app/~(transfers)/~transfers.create.route.tsx",
      "parent": "/_app"
    },
    "/_app/wallets/$walletId": {
      "filePath": "~_app/~(wallets)/~wallets.$walletId.route.tsx",
      "parent": "/_app"
    },
    "/_app/wallets/create": {
      "filePath": "~_app/~(wallets)/~wallets.create.route.tsx",
      "parent": "/_app"
    },
    "/_app/budgets/": {
      "filePath": "~_app/~(budgets)/~budgets.index.route.tsx",
      "parent": "/_app"
    },
    "/_app/records/": {
      "filePath": "~_app/~(records)/~records.index.route.tsx",
      "parent": "/_app"
    },
    "/_app/settings/": {
      "filePath": "~_app/~(settings)/~settings.index.route.tsx",
      "parent": "/_app"
    },
    "/_app/transfers/": {
      "filePath": "~_app/~(transfers)/~transfers.index.route.tsx",
      "parent": "/_app"
    },
    "/_app/wallets/": {
      "filePath": "~_app/~(wallets)/~wallets.index.route.tsx",
      "parent": "/_app"
    },
    "/_app/wallets/$walletId/edit": {
      "filePath": "~_app/~(wallets)/~wallets_.$walletId.edit.route.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
