/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/~__root";
import { Route as AppRouteImport } from "./../routes/~_app";
import { Route as OnboardingRouteRouteImport } from "./../routes/~onboarding.route";
import { Route as AppIndexRouteImport } from "./../routes/~_app/~index";
import { Route as AppwalletsWalletsIndexRouteRouteImport } from "./../routes/~_app/~(wallets)/~wallets.index.route";
import { Route as ApptransfersTransfersIndexRouteRouteImport } from "./../routes/~_app/~(transfers)/~transfers.index.route";
import { Route as AppsettingsSettingsIndexRouteRouteImport } from "./../routes/~_app/~(settings)/~settings.index.route";
import { Route as ApprecordsRecordsIndexRouteRouteImport } from "./../routes/~_app/~(records)/~records.index.route";
import { Route as AppbudgetsBudgetsIndexRouteRouteImport } from "./../routes/~_app/~(budgets)/~budgets.index.route";
import { Route as AppwalletsWalletsCreateRouteRouteImport } from "./../routes/~_app/~(wallets)/~wallets.create.route";
import { Route as AppwalletsWalletsWalletIdRouteRouteImport } from "./../routes/~_app/~(wallets)/~wallets.$walletId.route";
import { Route as ApptransfersTransfersCreateRouteRouteImport } from "./../routes/~_app/~(transfers)/~transfers.create.route";
import { Route as ApprecordsRecordsCreateRouteRouteImport } from "./../routes/~_app/~(records)/~records.create.route";
import { Route as ApprecordsRecordsRecordIdRouteRouteImport } from "./../routes/~_app/~(records)/~records.$recordId.route";
import { Route as AppbudgetsBudgetsCreateRouteRouteImport } from "./../routes/~_app/~(budgets)/~budgets.create.route";
import { Route as AppbudgetsBudgetsBudgetIdRouteRouteImport } from "./../routes/~_app/~(budgets)/~budgets.$budgetId.route";
import { Route as AppwalletsWalletsWalletIdEditRouteRouteImport } from "./../routes/~_app/~(wallets)/~wallets_.$walletId.edit.route";

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);
const AppwalletsWalletsIndexRouteRoute = AppwalletsWalletsIndexRouteRouteImport.update({
  id: "/(wallets)/wallets/",
  path: "/wallets",
  getParentRoute: () => AppRoute,
} as any);
const ApptransfersTransfersIndexRouteRoute = ApptransfersTransfersIndexRouteRouteImport.update({
  id: "/(transfers)/transfers/",
  path: "/transfers",
  getParentRoute: () => AppRoute,
} as any);
const AppsettingsSettingsIndexRouteRoute = AppsettingsSettingsIndexRouteRouteImport.update({
  id: "/(settings)/settings/",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);
const ApprecordsRecordsIndexRouteRoute = ApprecordsRecordsIndexRouteRouteImport.update({
  id: "/(records)/records/",
  path: "/records",
  getParentRoute: () => AppRoute,
} as any);
const AppbudgetsBudgetsIndexRouteRoute = AppbudgetsBudgetsIndexRouteRouteImport.update({
  id: "/(budgets)/budgets/",
  path: "/budgets",
  getParentRoute: () => AppRoute,
} as any);
const AppwalletsWalletsCreateRouteRoute = AppwalletsWalletsCreateRouteRouteImport.update({
  id: "/(wallets)/wallets/create",
  path: "/wallets/create",
  getParentRoute: () => AppRoute,
} as any);
const AppwalletsWalletsWalletIdRouteRoute = AppwalletsWalletsWalletIdRouteRouteImport.update({
  id: "/(wallets)/wallets/$walletId",
  path: "/wallets/$walletId",
  getParentRoute: () => AppRoute,
} as any);
const ApptransfersTransfersCreateRouteRoute = ApptransfersTransfersCreateRouteRouteImport.update({
  id: "/(transfers)/transfers/create",
  path: "/transfers/create",
  getParentRoute: () => AppRoute,
} as any);
const ApprecordsRecordsCreateRouteRoute = ApprecordsRecordsCreateRouteRouteImport.update({
  id: "/(records)/records/create",
  path: "/records/create",
  getParentRoute: () => AppRoute,
} as any);
const ApprecordsRecordsRecordIdRouteRoute = ApprecordsRecordsRecordIdRouteRouteImport.update({
  id: "/(records)/records/$recordId",
  path: "/records/$recordId",
  getParentRoute: () => AppRoute,
} as any);
const AppbudgetsBudgetsCreateRouteRoute = AppbudgetsBudgetsCreateRouteRouteImport.update({
  id: "/(budgets)/budgets/create",
  path: "/budgets/create",
  getParentRoute: () => AppRoute,
} as any);
const AppbudgetsBudgetsBudgetIdRouteRoute = AppbudgetsBudgetsBudgetIdRouteRouteImport.update({
  id: "/(budgets)/budgets/$budgetId",
  path: "/budgets/$budgetId",
  getParentRoute: () => AppRoute,
} as any);
const AppwalletsWalletsWalletIdEditRouteRoute =
  AppwalletsWalletsWalletIdEditRouteRouteImport.update({
    id: "/(wallets)/wallets_/$walletId/edit",
    path: "/wallets/$walletId/edit",
    getParentRoute: () => AppRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/onboarding": typeof OnboardingRouteRoute;
  "/": typeof AppIndexRoute;
  "/budgets/$budgetId": typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  "/budgets/create": typeof AppbudgetsBudgetsCreateRouteRoute;
  "/records/$recordId": typeof ApprecordsRecordsRecordIdRouteRoute;
  "/records/create": typeof ApprecordsRecordsCreateRouteRoute;
  "/transfers/create": typeof ApptransfersTransfersCreateRouteRoute;
  "/wallets/$walletId": typeof AppwalletsWalletsWalletIdRouteRoute;
  "/wallets/create": typeof AppwalletsWalletsCreateRouteRoute;
  "/budgets": typeof AppbudgetsBudgetsIndexRouteRoute;
  "/records": typeof ApprecordsRecordsIndexRouteRoute;
  "/settings": typeof AppsettingsSettingsIndexRouteRoute;
  "/transfers": typeof ApptransfersTransfersIndexRouteRoute;
  "/wallets": typeof AppwalletsWalletsIndexRouteRoute;
  "/wallets/$walletId/edit": typeof AppwalletsWalletsWalletIdEditRouteRoute;
}
export interface FileRoutesByTo {
  "/onboarding": typeof OnboardingRouteRoute;
  "/": typeof AppIndexRoute;
  "/budgets/$budgetId": typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  "/budgets/create": typeof AppbudgetsBudgetsCreateRouteRoute;
  "/records/$recordId": typeof ApprecordsRecordsRecordIdRouteRoute;
  "/records/create": typeof ApprecordsRecordsCreateRouteRoute;
  "/transfers/create": typeof ApptransfersTransfersCreateRouteRoute;
  "/wallets/$walletId": typeof AppwalletsWalletsWalletIdRouteRoute;
  "/wallets/create": typeof AppwalletsWalletsCreateRouteRoute;
  "/budgets": typeof AppbudgetsBudgetsIndexRouteRoute;
  "/records": typeof ApprecordsRecordsIndexRouteRoute;
  "/settings": typeof AppsettingsSettingsIndexRouteRoute;
  "/transfers": typeof ApptransfersTransfersIndexRouteRoute;
  "/wallets": typeof AppwalletsWalletsIndexRouteRoute;
  "/wallets/$walletId/edit": typeof AppwalletsWalletsWalletIdEditRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/onboarding": typeof OnboardingRouteRoute;
  "/_app": typeof AppRouteWithChildren;
  "/_app/": typeof AppIndexRoute;
  "/_app/(budgets)/budgets/$budgetId": typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  "/_app/(budgets)/budgets/create": typeof AppbudgetsBudgetsCreateRouteRoute;
  "/_app/(records)/records/$recordId": typeof ApprecordsRecordsRecordIdRouteRoute;
  "/_app/(records)/records/create": typeof ApprecordsRecordsCreateRouteRoute;
  "/_app/(transfers)/transfers/create": typeof ApptransfersTransfersCreateRouteRoute;
  "/_app/(wallets)/wallets/$walletId": typeof AppwalletsWalletsWalletIdRouteRoute;
  "/_app/(wallets)/wallets/create": typeof AppwalletsWalletsCreateRouteRoute;
  "/_app/(budgets)/budgets/": typeof AppbudgetsBudgetsIndexRouteRoute;
  "/_app/(records)/records/": typeof ApprecordsRecordsIndexRouteRoute;
  "/_app/(settings)/settings/": typeof AppsettingsSettingsIndexRouteRoute;
  "/_app/(transfers)/transfers/": typeof ApptransfersTransfersIndexRouteRoute;
  "/_app/(wallets)/wallets/": typeof AppwalletsWalletsIndexRouteRoute;
  "/_app/(wallets)/wallets_/$walletId/edit": typeof AppwalletsWalletsWalletIdEditRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/onboarding"
    | "/"
    | "/budgets/$budgetId"
    | "/budgets/create"
    | "/records/$recordId"
    | "/records/create"
    | "/transfers/create"
    | "/wallets/$walletId"
    | "/wallets/create"
    | "/budgets"
    | "/records"
    | "/settings"
    | "/transfers"
    | "/wallets"
    | "/wallets/$walletId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/onboarding"
    | "/"
    | "/budgets/$budgetId"
    | "/budgets/create"
    | "/records/$recordId"
    | "/records/create"
    | "/transfers/create"
    | "/wallets/$walletId"
    | "/wallets/create"
    | "/budgets"
    | "/records"
    | "/settings"
    | "/transfers"
    | "/wallets"
    | "/wallets/$walletId/edit";
  id:
    | "__root__"
    | "/onboarding"
    | "/_app"
    | "/_app/"
    | "/_app/(budgets)/budgets/$budgetId"
    | "/_app/(budgets)/budgets/create"
    | "/_app/(records)/records/$recordId"
    | "/_app/(records)/records/create"
    | "/_app/(transfers)/transfers/create"
    | "/_app/(wallets)/wallets/$walletId"
    | "/_app/(wallets)/wallets/create"
    | "/_app/(budgets)/budgets/"
    | "/_app/(records)/records/"
    | "/_app/(settings)/settings/"
    | "/_app/(transfers)/transfers/"
    | "/_app/(wallets)/wallets/"
    | "/_app/(wallets)/wallets_/$walletId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  OnboardingRouteRoute: typeof OnboardingRouteRoute;
  AppRoute: typeof AppRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(wallets)/wallets/": {
      id: "/_app/(wallets)/wallets/";
      path: "/wallets";
      fullPath: "/wallets";
      preLoaderRoute: typeof AppwalletsWalletsIndexRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(transfers)/transfers/": {
      id: "/_app/(transfers)/transfers/";
      path: "/transfers";
      fullPath: "/transfers";
      preLoaderRoute: typeof ApptransfersTransfersIndexRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(settings)/settings/": {
      id: "/_app/(settings)/settings/";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AppsettingsSettingsIndexRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(records)/records/": {
      id: "/_app/(records)/records/";
      path: "/records";
      fullPath: "/records";
      preLoaderRoute: typeof ApprecordsRecordsIndexRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(budgets)/budgets/": {
      id: "/_app/(budgets)/budgets/";
      path: "/budgets";
      fullPath: "/budgets";
      preLoaderRoute: typeof AppbudgetsBudgetsIndexRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(wallets)/wallets/create": {
      id: "/_app/(wallets)/wallets/create";
      path: "/wallets/create";
      fullPath: "/wallets/create";
      preLoaderRoute: typeof AppwalletsWalletsCreateRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(wallets)/wallets/$walletId": {
      id: "/_app/(wallets)/wallets/$walletId";
      path: "/wallets/$walletId";
      fullPath: "/wallets/$walletId";
      preLoaderRoute: typeof AppwalletsWalletsWalletIdRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(transfers)/transfers/create": {
      id: "/_app/(transfers)/transfers/create";
      path: "/transfers/create";
      fullPath: "/transfers/create";
      preLoaderRoute: typeof ApptransfersTransfersCreateRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(records)/records/create": {
      id: "/_app/(records)/records/create";
      path: "/records/create";
      fullPath: "/records/create";
      preLoaderRoute: typeof ApprecordsRecordsCreateRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(records)/records/$recordId": {
      id: "/_app/(records)/records/$recordId";
      path: "/records/$recordId";
      fullPath: "/records/$recordId";
      preLoaderRoute: typeof ApprecordsRecordsRecordIdRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(budgets)/budgets/create": {
      id: "/_app/(budgets)/budgets/create";
      path: "/budgets/create";
      fullPath: "/budgets/create";
      preLoaderRoute: typeof AppbudgetsBudgetsCreateRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(budgets)/budgets/$budgetId": {
      id: "/_app/(budgets)/budgets/$budgetId";
      path: "/budgets/$budgetId";
      fullPath: "/budgets/$budgetId";
      preLoaderRoute: typeof AppbudgetsBudgetsBudgetIdRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/(wallets)/wallets_/$walletId/edit": {
      id: "/_app/(wallets)/wallets_/$walletId/edit";
      path: "/wallets/$walletId/edit";
      fullPath: "/wallets/$walletId/edit";
      preLoaderRoute: typeof AppwalletsWalletsWalletIdEditRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute;
  AppbudgetsBudgetsBudgetIdRouteRoute: typeof AppbudgetsBudgetsBudgetIdRouteRoute;
  AppbudgetsBudgetsCreateRouteRoute: typeof AppbudgetsBudgetsCreateRouteRoute;
  ApprecordsRecordsRecordIdRouteRoute: typeof ApprecordsRecordsRecordIdRouteRoute;
  ApprecordsRecordsCreateRouteRoute: typeof ApprecordsRecordsCreateRouteRoute;
  ApptransfersTransfersCreateRouteRoute: typeof ApptransfersTransfersCreateRouteRoute;
  AppwalletsWalletsWalletIdRouteRoute: typeof AppwalletsWalletsWalletIdRouteRoute;
  AppwalletsWalletsCreateRouteRoute: typeof AppwalletsWalletsCreateRouteRoute;
  AppbudgetsBudgetsIndexRouteRoute: typeof AppbudgetsBudgetsIndexRouteRoute;
  ApprecordsRecordsIndexRouteRoute: typeof ApprecordsRecordsIndexRouteRoute;
  AppsettingsSettingsIndexRouteRoute: typeof AppsettingsSettingsIndexRouteRoute;
  ApptransfersTransfersIndexRouteRoute: typeof ApptransfersTransfersIndexRouteRoute;
  AppwalletsWalletsIndexRouteRoute: typeof AppwalletsWalletsIndexRouteRoute;
  AppwalletsWalletsWalletIdEditRouteRoute: typeof AppwalletsWalletsWalletIdEditRouteRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppbudgetsBudgetsBudgetIdRouteRoute: AppbudgetsBudgetsBudgetIdRouteRoute,
  AppbudgetsBudgetsCreateRouteRoute: AppbudgetsBudgetsCreateRouteRoute,
  ApprecordsRecordsRecordIdRouteRoute: ApprecordsRecordsRecordIdRouteRoute,
  ApprecordsRecordsCreateRouteRoute: ApprecordsRecordsCreateRouteRoute,
  ApptransfersTransfersCreateRouteRoute: ApptransfersTransfersCreateRouteRoute,
  AppwalletsWalletsWalletIdRouteRoute: AppwalletsWalletsWalletIdRouteRoute,
  AppwalletsWalletsCreateRouteRoute: AppwalletsWalletsCreateRouteRoute,
  AppbudgetsBudgetsIndexRouteRoute: AppbudgetsBudgetsIndexRouteRoute,
  ApprecordsRecordsIndexRouteRoute: ApprecordsRecordsIndexRouteRoute,
  AppsettingsSettingsIndexRouteRoute: AppsettingsSettingsIndexRouteRoute,
  ApptransfersTransfersIndexRouteRoute: ApptransfersTransfersIndexRouteRoute,
  AppwalletsWalletsIndexRouteRoute: AppwalletsWalletsIndexRouteRoute,
  AppwalletsWalletsWalletIdEditRouteRoute: AppwalletsWalletsWalletIdEditRouteRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  OnboardingRouteRoute: OnboardingRouteRoute,
  AppRoute: AppRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
