export const ERROR_CODES = {
  AUTH: {
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    FORBIDDEN: "AUTH_FORBIDDEN",
  },
  WALLET: {
    NOT_FOUND: "WALLET_NOT_FOUND",
    CONFLICT: "WALLET_CONFLICT",
  },
  RECORD: {
    NOT_FOUND: "RECORD_NOT_FOUND",
  },
  BUDGET: {
    NOT_FOUND: "BUDGET_NOT_FOUND",
  },
  TRANSFER: {
    NOT_FOUND: "TRANSFER_NOT_FOUND",
  },
  DEBT_LOAN: {
    NOT_FOUND: "DEBT_LOAN_NOT_FOUND",
    ALREADY_RESOLVED: "DEBT_LOAN_ALREADY_RESOLVED",
    WRONG_TYPE: "DEBT_LOAN_WRONG_TYPE",
    INSUFFICIENT_BALANCE: "DEBT_LOAN_INSUFFICIENT_BALANCE",
  },
  SETTINGS: {
    NOT_FOUND: "SETTINGS_NOT_FOUND",
    CONFLICT: "SETTINGS_CONFLICT",
  },
  VALIDATION: {
    INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  },
  INTERNAL: {
    SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  },
} as const;
