export const ERROR_CODES = {
  AUTH: {
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    FORBIDDEN: "AUTH_FORBIDDEN",
  },
  WALLET: {
    NOT_FOUND: "WALLET_NOT_FOUND",
    CONFLICT: "WALLET_CONFLICT",
  },
  VALIDATION: {
    INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  },
  INTERNAL: {
    SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  },
} as const;
